version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./app/controllers:/app/controllers
      - ./app/data:/app/data
      - ./app/models:/app/models
      - ./app/routers:/app/routers
      - ./app/views:/app/views
      - ./public:/app/public
    environment:
      NODE_ENV: production
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: weatherapp
      POSTGRES_PASSWORD: weatherapp
      POSTGRES_DB: weatherapp
    volumes:
      - ./app/data/db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
